### ISSUE TITLE
Ast visitors should visit C++ references instead of pointers

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/nmodl#294]
Passing a pointer means that it can be `nullptr`. By reading the existing visitors, it is not seem to be the case. Visiting C++ references is simpler and removes the doubt that `nullptr` is passed which can lead to either segmentation faults of useless paranoïd `nullptr` checks

**Comment by cattabiani** [comment]
there are a few things that are `optional: true`. They can be nullptr I think. @pramodk can correct me if I am wrong.

**Comment by cattabiani** [comment]
removing the "optional" keyword in the yaml file in conjunction to your suggestion could be possible (and suggested). However, I do not have the experience to say if it would be a Pandora's box or not

**Comment by tristan0x** [comment]
> there are a few things that are `optional: true` (i.e. Unit in DoubleUnit).
> They can be nullptr I think. @pramodk can correct me if I am wrong.

Thank you for this information. I didn't know the `optional` thing

**Comment by ohm314** [comment]
We had looked at this last year already and I think there was an additional issue why this was not easily possible, which is why I finally did not push a change. I can't remember right now what it was exactly (apart from the optional children) but I'll let you know if I remember.

**Comment by pramodk** [comment]
> We had looked at this last year already and I think there was an additional issue why this was not  easily possible, which is why I finally did not push a change. I can't remember right now what it was exactly 

I was about to mention the same discussion from the last year. I also don't remember well the conclusion.

But, we also thought this is doable but later backtracked for some reason (not sure if it was technical or just time constraint).

At the beginning, I started with raw pointers because of two reasons : in the beginning smart pointers were not used in Ast (due to Bison) and I implemented most of the stuff by looking at existing project. For example,  some visitor that I initially looked at [here](https://clang.llvm.org/docs/RAVFrontendAction.html) and [here](https://clang.llvm.org/doxygen/classclang_1_1ento_1_1ConditionBRVisitor.html) used raw pointers. But we can also see [the visitors with references](https://llvm.org/doxygen/classllvm_1_1InstVisitor.html) used. So I think this should be doable.

By the way, this question I have seen few times, for example this [Stackoveflow](https://stackoverflow.com/questions/54287897/visitor-pattern-apply-on-shared-ptr-or-raw-pointer) one.
