### ISSUE TITLE
Move nmodl python files into subdirectory

### ISSUE THREAD

**Issue by ohm314** [BlueBrain/nmodl#462]
Currently the nmodl python module files are in a top level directory called `nmodl`. Having the same name as the package itself it often leads to confusion especially when testing the python package. Various scenarios fail because python uses the current working dir as a search dir for modules. This way the local `nmodl` directory will take precedence over an installed `nmodl` python module (eg. in `site-packages`). We have several workarounds to address this, but we keep finding scenarios, where confusing errors show up.
A proper fix is needed. For example the `nmodl` directory should be moved into another dir, maybe named `pkg`. It is not sufficient to move the directory as this will entail a number of changes in the build system and CI:

- CMakeLists.txt need to be checked and fixed
- setup.py needs to be checked and fixed
- azure CI will need checking for both the testing and wheel building pipelines
- travis CI might also need a check

This list is non-exhaustive but should cover most of what is needed.

**Comment by pramodk** [comment]
@alkino : this is for the master branch.

**Comment by cattabiani** [comment]
this is difficult to do in python since the name of the module IS the name of the top level folder (there there is __init __.py, the one that you want to rename). You could stuff the folder in another folder (i.e. `nmodl/python/nmodl`) but you need to change the source root in setup.py to something that is not `.`. This is very unusual for python. Also the docs build will probably fail since it leverages the fact that the module is in the local dir. Sometimes it is a feature, sometimes it is a bug

**Comment by cattabiani** [comment]
anyway, if you really want to put it into something like: `nmodl/pkg/nmodl` you can follow this:

https://stackoverflow.com/questions/14417236/setup-py-renaming-src-package-to-project-name
