### ISSUE TITLE
Implement "blackbox" solvers as fallback if sympy analytic fails

### ISSUE THREAD

**Issue by lkeegan** [BlueBrain/nmodl#60]
- would be useful for testing
- calculate Jacobian numerically with difference approx
- would also work with if statements, verbatim blocks, etc
- performance not critical

**Comment by pramodk** [comment]
@cattabiani : could you take a look at this ticket and understand **_overall scope_** off this ticket by reviewing existing solver implementation and references issues?

The overall idea is that if sympy fails then we need a fallback solver that we can rely on. This is needed to  deprecate mod2c completely.

**Comment by cattabiani** [comment]
@pramodk do we already have a mod file where sympy fails?

**Comment by pramodk** [comment]
@cattabiani : off the top of my head I don't remember any mod file which was failing with sympy solver. But may be you can build artificial one ? You can also see some motivation in #55 and #85.

**Comment by cattabiani** [comment]
I am still reading literature about the latest methods around. Looks like numerical differentiation is used extensively in deep learning and there are already many tools available. [Automatic differentiation](https://en.wikipedia.org/wiki/Automatic_differentiation) looks superior (for a computer program) than the numerical one and avoids a lot of the pitfalls. Now the question is: what tool do we want to use? 

A summary of what I have found:

- [autograd](https://github.com/HIPS/autograd): still maintained but not developed anymore (good reviews)
- [tensorflow](https://www.tensorflow.org/guide/autodiff), [pytorch](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html) quite big projects. Do we need cannons?
- [auto_diff](https://pypi.org/project/auto-diff/) very recent and probably developed by a very small team

if you have experience on the topic I am happy to hear your ideas @ferdonline @pramodk

**Comment by pramodk** [comment]
> if you have experience on the topic 

no...not much! I wonder if @ohm314  remember anything on this topic because IIRC he had discussions.

> tensorflow, pytorch quite big projects. Do we need cannons?

certainly not! 

@lkeegan : could I ask you if you remember what were were planning and possible ways to implement this? (of course if you remember)

**Comment by cattabiani** [comment]
After some [research](https://arxiv.org/abs/1502.05767) (thx @ohm314 ) here are a few notes.

- Functions with an infinite ammount of points in which they are not C1 are probably of no interest for scientists
- The "big" cases that are not completely handled by nmodl yet are:
  - control flow blocks
  - verbatim blocks inside derivative ones
  - ?
- Automatic Differentiation pares the evaluation of a function in a point with the evaluation of its derivatives (in that point). Basic operations are derived symbolically, computed to simplify expression and then chained to get the final Jacobian. This has the following advantages:
  - precise up to machine precision (like symbolic differentiation)
  - no "equation swelling" (better than symbolic differentiation and not prone to a possible "early sympy surrender" due to equations that are too long)
  - no problem with control flows (and I guess with verbatim blocks) (numerical differentiation in these cases could be very difficult/impossible to implement correctly)

**Comment by lkeegan** [comment]
@pramodk the idea was to have a version of the newton solver that used a simple numerical differentiation approximation to the jacobian as a fall back for the cases where sympy could not be used to provide the analytic jacobian (e.g. verbatim blocks), which was implemented here: https://github.com/BlueBrain/nmodl/blob/master/src/solver/newton/newton.hpp#L80-L152
I think if the sympy pass fails nmodl should use this version of the newton solver instead, although I can't remember if this was fully implemented - I remember getting lots of help from @ohm314 on this so maybe he remembers..
But if it would be possible to replace this with an AD method that would definitely be an improvement!

**Comment by cattabiani** [comment]
I checked and I did not find any practical case where sympy analytic can fail. AD is better in case of "equation swelling". However, for hand-written equations that problem is minor/non-existant. Thus, I close this issue. If there are any real case scenario appearing I will reinvestigate this issue
