### ISSUE TITLE
olfactory-bulb-3d test : CoreNRN+NMODL gives completely different results compared to CoreNRN+MOD2C & NRN

### ISSUE THREAD

**Issue by kotsaloscv** [BlueBrain/nmodl#699]
I have executed the olfactory-bulb-3d test and CoreNRN+NMODL gives completely different results compared to CoreNRN+MOD2C. Additionally, CoreNRN+MOD2C gives exactly the same results as pure NRN.

To reproduce (in BB5):
1. Clone olfactory test from `https://github.com/kotsaloscv/olfactory-bulb-3d.git` and checkout to `2to3` branch.
2. Install the different libraries, i.e. NMODL, CoreNRN with MOD2C, CoreNRN with NMODL. This is done by running the `install.sh` script.
3. Run the simulations from the `run_cpu.sh` script.
4. The generated spike files can be found under the `sim` folder (`0_*.spk, 1_*.spk, 2_*.spk`).

While NRN & CoreNRN+MOD2C give about 100K spikes, CoreNRN+NMODL gives about 2.5M spikes. I have executed the simulations with 4 & 36 MPI tasks and I get the same results.

**Comment by iomaganaris** [comment]
Validation was done using https://github.com/iomaganaris/olfactory-bulb-3d/tree/2to3_bench.
Spikes were mostly similar between NEURON and CoreNEURON runs on CPU and GPU with only a very small fraction of them shifted in time due to floating point differences (conclusion based on past experiences).
To reproduce the results:
```
git clone -b 2to3_bench git@github.com:iomaganaris/olfactory-bulb-3d.git
cd olfactory-bulb-3d.git
sh install.sh
sbatch run_cpu_bench.sh
sbatch run_gpu_bench.sh
```
