### ISSUE TITLE
Program is not inheriting from Node but from AST

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#79]
Currently we have : 

```
class Program : public AST {
private:
```

but rest nodes inherit from `AST->Node->XX`. Check why this was done and whether Program can inherit from node as well.

**Comment by iomaganaris** [comment]
After some investigation I figured out that `ast::Program` is created by the `all` rule of the parser. This means that in the beginning of the parsing of a file there is an `ast::Prorgam` created. Then every top level block is added to the `ast::Program` in the public member `NodeVector blocks`. My guess is that it doesn't inherit from `Node` to distinguish it from other types of `Node`s due to its special nature.
After making `Program` inherit from `Node` by editing `nmodl.yaml` there were no issues with the included tests of `NMODL` or using `NMODL` to build `CoreNeuron`.
