### ISSUE TITLE
Exceptions from`__getattribute__` in a visitor don't propagate

### ISSUE THREAD

**Issue by ramcdougal** [BlueBrain/nmodl#881]
Exceptions from`__getattribute__` in a visitor don't propagate. For example, this code
```python
import nmodl.dsl as nmodl
from neuron import h
from nmodl import visitor
from typing import Any


class TitleVisitor(visitor.AstVisitor):
    def __getattribute__(self, name: str) -> Any:
        print("*** raising an exception now ***")
        raise Exception("uh oh")

class NeuroMLVisitor(visitor.AstVisitor):
    def visit_model(self, node):
        print("starting title_visitor")
        title_visitor = TitleVisitor()
        node.visit_children(title_visitor)
        print("title_visitor completed without detected Exception")    

my_ast = nmodl.NmodlDriver().parse_string(h.pas.code)
nmv = NeuroMLVisitor()
my_ast.visit_children(nmv)
```

displays

```
starting title_visitor
*** raising an exception now ***
title_visitor completed without detected Exception
```

In particular, the `visit_model` code has no way to know that something went wrong in the `__getattribute__`. (By contrast, exceptions in e.g. `visit_string` do propagate.)

Calling ` TitleVisitor().llama` successfully raises an `AttributeError` exception.

**Comment by ramcdougal** [comment]
Raising an `AttributeError` instead of an `Exception` still fails to pass the exception to `visit_model`.

**Comment by alkino** [comment]
It will not be possible to fix that.
From c++ side you receive an exception. The C API of Python only return a boolean, hard to know if the error is because of a AttributeError or no.
As the class is override when an error occured pybind choose to return a function pointer to the C++ base implementation.

So, we can do nothing on our side and it will surely never be fixed.

Sorry.
