### ISSUE TITLE
Deprecate EXTERNAL constructs

### ISSUE THREAD

**Issue by iomaganaris** [BlueBrain/nmodl#956]
Check the `EXTERNAL` construct implementation and documentation in `NEURON` and add related unit test in `NMODL`.

**Comment by alkino** [comment]
After discussion with @iomaganaris and @alkino we figured out that none of the mod files in model-db with `EXTERNAL` make sense. So I think we should either rethink how `EXTERNAL` should work in the mod files (with @nrnhines) or just deprecate the feature. The mod files in model-db either will never work with CoreNEURON the way they are using the `EXTERNAL` (and other variables) or in NEURON they will have bugs since `EXTERNAL` variables that are `GLOBAL`s are being written inside `BREAKPOINT` or `STATE` blocks.

**Comment by nrnhines** [comment]
https://nrn.readthedocs.io/en/latest/python/modelspec/programmatic/mechanisms/nmodl2.html#external

Harks back to the days where simulations were only a single stream of serial execution. Many circumstances where that is still the case. But nowadays its an obvious race condition.

**Comment by alkino** [comment]
what should we do with EXTERNAL? Deprecate the feature?

**Comment by nrnhines** [comment]
I will review the usage of EXTERNAL in nrn-modeldb-ci and consider their underlying purpose and if/how they can be modified to make sense in parallel environments.
```
116769
SpineCaModel/canmda.mod	EXTERNAL i2_nmda, g2_nmda, i2_ampa, g2_ampa, irtype_car
SpineCaModel/ampa.mod	EXTERNAL Area_canmda
SpineCaModel/nmda.mod	EXTERNAL Area_canmda
SpineCaModel/car.mod	EXTERNAL Area_canmda

144385
ShepherdBrayton1979/mod/canmda.mod	EXTERNAL i2_nmda, g2_nmda, i2_ampa, g2_ampa, irtype_car
ShepherdBrayton1979/mod/ampa.mod	EXTERNAL Area_canmda
ShepherdBrayton1979/mod/nmda.mod	EXTERNAL Area_canmda
ShepherdBrayton1979/mod/car.mod	EXTERNAL Area_canmda

50997
Ribbon/ribbon_tiger.mod     EXTERNAL mod_modulator
Ribbon/rib_ufp.mod     EXTERNAL mod_modulator

258643
snc_da_rumbell_2019/mechanisms/kerg_sncda.mod    EXTERNAL apc_metap, fpc_metap
snc_da_rumbell_2019/mechanisms/hcn_sncda.mod    EXTERNAL apc_metap, fpc_metap
snc_da_rumbell_2019/mechanisms/kv4_a_sncda.mod    EXTERNAL apc_metap, fpc_metap
snc_da_rumbell_2019/mechanisms/sk_sncda.mod    EXTERNAL apc_metap, fpc_metap
snc_da_rumbell_2019/mechanisms/cal_sncda.mod    EXTERNAL apc_metap, fpc_metap
snc_da_rumbell_2019/mechanisms/cat_sncda.mod    EXTERNAL apc_metap, fpc_metap
snc_da_rumbell_2019/mechanisms/Cad.mod    EXTERNAL apc_metap, fpc_metap
snc_da_rumbell_2019/mechanisms/kv2_dr_sncda.mod    : EXTERNAL pc1_metap, pc3_metap, pc24_metap
snc_da_rumbell_2019/mechanisms/leak_dop.mod    EXTERNAL apc_metap, fpc_metap

231427
reproduction/canmda.mod	EXTERNAL i2_nmda, g2_nmda, i2_ampa, g2_ampa, irtype_car
reproduction/ampa.mod	EXTERNAL Area_canmda
reproduction/nmda.mod	EXTERNAL Area_canmda
reproduction/car.mod	EXTERNAL Area_canmda
```

**Comment by nrnhines** [comment]
It appears that only 258643 and 231427 are safe. The former because the assignment to mod_modulator is in a modfile alphabetically earlier than the modfiles where it is evaluated and used. The latter because the EXTERNAL variables are not used at all in those mod files. The other models are all of the same family and only work in the context of a single compartment.

The use of Area_canmda should be replaced by area (the area of the compartment in um/cm2) and all the other uses
can be avoided with POINTER or combining the mod files 

It seems reasonable to deprecate the keyword. It was originally intended to make (pure) functions defined in one mod file available
for calling from other mod files.
